replicaCount: 1

route:
  enabled: false

serviceMesh:
  route: true
  sidecar: true

hostname: 

deployment:
  strategy: Rolling

image:
  repository: "obsidiandynamics/kafdrop"
  tag: "3.27.0"
  pullPolicy: Always

rbac:
  create: true

serviceAccount:
  create: true

host:

jvm:
  opts: "-Xms2048M -Xmx2048M"
jmx:
  port: 8686

nameOverride: ""
fullnameOverride: ""

cmdArgs: "--message.format=AVRO"

server:
  port: 9000
  servlet:
    contextPath: /

service:
  annotations: {}
  type: ClusterIP
  port: 9000


resources:
  limits:
   cpu: 1
   memory: 2048Mi
  requests:
    cpu: 300m
    memory: 2048Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

mountProtoDesc: 
  enabled: false
  hostPath:
