{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "chart.fullname" . }}
    helm.sh/chart: {{ include "chart.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
roleRef:
  kind: Role
  name: {{ include "chart.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "chart.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
