{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "chart.fullname" . }}
    helm.sh/chart: {{ include "chart.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
imagePullSecrets:
  - name: artifactory-docker
{{- end -}}
